server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: postgres
    password: Ai37o6qx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect    